# hydra.job.chdir: false
hydra:
  searchpath:
  # see https://hydra.cc/docs/advanced/search_path/
  # - file://../cfg
  - isaac-training/third_party/D_Learning/cfg
headless: 1 # 是否显示isaac GUI
physics_gpu: 0
physics_engine: physx5

# sim: ${task.sim} # 需要输入当前的task名：例如python xxxx task=Forest， 会找到cfg/task/Forest.yaml
# env: ${task.env} # 同样在Forest.yaml中有env变量

# total_frames: 150_000_000
total_frames: 1000000
max_iters: -1
eval_interval: -1
save_interval: 5
seed: 2

num_minibatches: 256

viewer:
  resolution: [960, 720]
  eye: [8, 0., 12.]
  lookat: [0., 0., 8.]

# oc.select: https://omegaconf.readthedocs.io/en/2.1_branch/custom_resolvers.html#oc-decode
wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity: rfly
  project: omnidrones
  # mode: disabled # set to 'disabled' when debugging locally
  mode: cloud
  run_id: 
  monitor_gym: True
  tags: 

# checkpoint_path: swanlog/run-20250826_110601-34db79b4
checkpoint_path: null
checkpoint_episode: final
# checkpoint_path: swanlog/run-20250723_134337-9a2696a9
# checkpoint_episode: 3

defaults:
  - task: DlearningHoverEnv
  - algo: hierarchicaldlearning
  - _self_

env:
  num_envs: 2048
  env_spacing: 0
  max_episode_length: 256
  # pos 400 
  # atti 64

sim:
  dt: 0.016
  substeps: 1
  gravity: [0, 0, -9.81]
  replicate_physics: false
  use_flatcache: true
  use_gpu_pipeline: true
  device: "cuda:0"

  solver_type: 1
  use_gpu: True # set to False to run on CPU
  bounce_threshold_velocity: 0.2
  friction_offset_threshold: 0.04
  friction_correlation_distance: 0.025
  enable_stabilization: True
  # enable_scene_query_support: true # for Lidars (to be implemented)

  # GPU buffers
  gpu_max_rigid_contact_count: 524288
  gpu_max_rigid_patch_count: 163840 # 33554432
  gpu_found_lost_pairs_capacity: 4194304
  gpu_found_lost_aggregate_pairs_capacity: 33554432
  gpu_total_aggregate_pairs_capacity: 4194304
  gpu_max_soft_body_contacts: 1048576
  gpu_max_particle_contacts: 1048576
  gpu_heap_capacity: 67108864
  gpu_temp_buffer_capacity: 16777216
  gpu_max_num_partitions: 8